export const email = "suckrowpierre@gmail.com"
export const linkedin = "https://www.linkedin.com/in/pierre-louis-suckrow/"
export const github = "https://github.com/suckrowPierre/"
export const instagram = "https://www.instagram.com/pierrelouissuckrow/"
export const researchGate = "https://www.researchgate.net/profile/Pierre-Louis-Suckrow"